Introduce support for authzed
quarkiverse/quarkus-zanzibar pull request #14
Opened 2022-09-24 11:33 UTC by iocanel

The pull request implements a RelationshipManager based on authzed with all needed bells and whistles.

2022-09-26 08:47 UTC, kdubb commented
Awesome... gonna look this over and merge tomorrow

2022-10-07 21:49 UTC, kdubb requested changes
Need to cleanup some copy/paste remnants from OpenFGA adapter.

2022-10-07 21:49 UTC, kdubb commented on zanzibar-authzed/deployment/src/test/java/io/quarkiverse/zanzibar/openfga/test/ZanzibarOpenFGADevModeTest.java
> +public class ZanzibarOpenFGADevModeTest {
Class & file should be named for Authzed

2022-10-07 21:49 UTC, kdubb commented on zanzibar-authzed/deployment/src/test/java/io/quarkiverse/zanzibar/openfga/test/ZanzibarOpenFGATest.java
> +public class ZanzibarOpenFGATest {
Class & file should be named for Authzed

2022-10-07 21:49 UTC, kdubb commented on zanzibar-authzed/runtime/src/main/resources/META-INF/quarkus-extension.yaml
> +name: Zanzibar Openfga
Need to reference Authzed here

2022-10-08 01:03 UTC, kdubb commented
The README should be updated as well to include support for Authzed.

2022-11-09 20:03 UTC, kdubb commented
@iocanel I'm looking to get Zanzibar "ready" for Quarkus 3. Can we get this cleaned up so I can merge it? I'm working on docs and a quickstart it would be nice to support both OpenFGA and Authzed for a `1.0` release.

2022-11-09 20:09 UTC, iocanel commented
Ok

2022-11-11 14:17 UTC, iocanel commented
@kdubb: applied feedback.

2022-12-13 17:39 UTC, merged